modLoader = "javafml"
loaderVersion = "[32,)"
license="MIT"

[[mods]]
    modId = "dolt_compat"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    authors = "DoltHHaven"
    credits = "Dolt"
    license="MIT"
    displayName = "Dolt Compat"
    description = '''
    Adds Doltish Compat to some not-doltish mods.
    '''

[[dependencies.dolt_compat]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2,1.19.3)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.dolt_compat]]
    modId = "forge"
    mandatory = true
    versionRange = "[43.2.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.dolt_compat]]
    modId = "environmental"
    mandatory = true
    versionRange = "[3.1.0,)"
    ordering = "NONE"
    side = "BOTH"


[[dependencies.dolt_compat]]
    modId = "quark"
    mandatory = true
    versionRange = "[3.4,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.dolt_compat]]
    modId = "farmersdelight"
    mandatory = true
    versionRange = "[1.2.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.dolt_compat]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[6.1.2,)"
    ordering = "AFTER"
    side = "BOTH"